buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // AGP வெர்ஷனை இங்கே மாற்றலாம்
        classpath 'com.android.tools.build:gradle:7.4.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
